"""empty message

Revision ID: 448b0a199fc9
Revises: 461fca9b79ed
Create Date: 2025-02-14 12:18:25.464235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '448b0a199fc9'
down_revision = '461fca9b79ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
