"""empty message

Revision ID: 461fca9b79ed
Revises: f8690773cd7f
Create Date: 2025-02-14 12:17:09.475538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '461fca9b79ed'
down_revision = 'f8690773cd7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_column('gender')
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('gender', sa.VARCHAR(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
