"""empty message

Revision ID: 58582bf2112e
Revises: e71aafb326ad
Create Date: 2025-02-15 20:17:54.825837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58582bf2112e'
down_revision = 'e71aafb326ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_column('favorite')

    # ### end Alembic commands ###
