"""empty message

Revision ID: 991d858563ea
Revises: 58582bf2112e
Create Date: 2025-02-15 20:47:21.823359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '991d858563ea'
down_revision = '58582bf2112e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('people_id', sa.Integer(), nullable=True),
    sa.Column('planet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['people_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['planet_id'], ['planet.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_column('favorite')

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.drop_column('favorite')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite', sa.VARCHAR(length=80), autoincrement=False, nullable=False))

    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite', sa.VARCHAR(length=80), autoincrement=False, nullable=True))

    op.drop_table('favorites')
    # ### end Alembic commands ###
