"""empty message

Revision ID: e71aafb326ad
Revises: ec65666200bf
Create Date: 2025-02-15 20:10:30.503035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e71aafb326ad'
down_revision = 'ec65666200bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hair_color', sa.String(length=80), nullable=True))
        batch_op.drop_column('hair__color')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hair__color', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('hair_color')

    # ### end Alembic commands ###
