"""empty message

Revision ID: ec65666200bf
Revises: 52c91d3bc5dc
Create Date: 2025-02-15 10:12:42.365273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec65666200bf'
down_revision = '52c91d3bc5dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hair_color', sa.String(length=80), nullable=True))
        batch_op.drop_column('hair_color')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hair_color', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('hair_color')

    # ### end Alembic commands ###
